version: "3.8"

services:
  dagit:
    build:
      context: ./dagster
      dockerfile: Dockerfile.dagster
    ports:
      - "4002:4002"

  dagster_daemon:
    build:
      context: ./dagster
      dockerfile: Dockerfile.dagster

  valmi-db:
    ports:
      - "5432:5432"

  valmi-repo:
    build:
      context: ./dagster
      dockerfile: Dockerfile.usercode

  valmi-activation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: valmi-activation
    volumes:
      - .:/workspace:z

  valmi-app-backend:
    build:
      context: ./valmi-app-backend
      dockerfile: Dockerfile
    volumes:
      - ./valmi-app-backend:/workspace:z

  valmi-app:
    build:
      context: ./valmi-app
      dockerfile: Dockerfile
    env_file:
      - ./valmi-app/.env
    ports:
      - "3000:3000"
    container_name: valmi-app
    restart: on-failure
    networks:
      - valmi-network
    depends_on:
      - valmi-db
      - valmi-app-backend
    volumes:
      - ./valmi-app:/workspace:z
      - ./valmi-app/.env:/app/.env
  
  valmi-recommendation-engine:
    image: valmiio/valmi-recommendation-engine:latest
    env_file:
      - .env
    ports:
      - "8001:8001"
    container_name: valmi-recommendation-engine
    restart: on-failure
    networks:
      - valmi-network
    volumes:
      - ./valmi-app-backend/.env:/.env:z


networks:
  valmi-network:
    driver: bridge
    name: valmi-network
